#! /bin/bash
set -e

if [[ "$1" == "-h" ]] ||  [[ "$1" == "--help" ]]
then
    echo "Usage: ./install-dependencies";
    echo "This script installs all the necessary software to compile, upload, and run the autolocator code."
    echo "It's intended to run on Mac OSX and is not, at the moment, portable."
    exit
fi

if [[ ! $(which brew) ]]
then
    echo "Installing Homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
brew update

if [[ ! $(which arduino-cli) ]]
then
    echo "Installing Homebrew"
    brew install arduino-cli
fi

echo "All done!"
