#! /bin/bash
set -e

source script/env
assertBoardConnected

arduino-cli compile --fqbn $FQBN --output bin/Interface.hex 'src/Interface/Interface.ino'
arduino-cli upload --fqbn $FQBN --port $DEVICE --verbose --input bin/Interface.hex
head -3 $DEVICE
