#! /bin/bash
set -e

source script/env
assertBoardConnected

arduino-cli compile --fqbn $FQBN --output bin/Test.hex 'test/Test.ino'
arduino-cli upload --fqbn $FQBN --port $DEVICE --verbose --input bin/Test.hex
# This is a little annoying if there's a failure.
head -4 $DEVICE
